import os
import tempfile
from pathlib import Path

import gpxpy
import gpxpy.gpx

from nd_route_finder.domain.track import Track


class GpxTrackWriter:
    def write(self, track: Track, output_path: Path) -> Path:
        resolved_output = output_path.expanduser().resolve()
        if resolved_output.suffix.lower() != ".gpx":
            resolved_output = resolved_output.with_suffix(".gpx")

        resolved_output.parent.mkdir(parents=True, exist_ok=True)

        gpx = gpxpy.gpx.GPX()
        gpx.name = track.name
        gpx.description = "Generated by nd_route_finder"

        gpx_track = gpxpy.gpx.GPXTrack(name=track.name)
        gpx.tracks.append(gpx_track)

        point_count = 0
        for source_segment in track.segments:
            if not source_segment:
                continue
            segment = gpxpy.gpx.GPXTrackSegment()
            gpx_track.segments.append(segment)
            for point in source_segment:
                segment.points.append(
                    gpxpy.gpx.GPXTrackPoint(
                        latitude=point.latitude,
                        longitude=point.longitude,
                        elevation=point.elevation,
                    )
                )
                point_count += 1

        if point_count < 2:
            raise RuntimeError(
                f"Generated route contains only {point_count} GPX point(s); refusing to save an invalid route."
            )

        xml = gpx.to_xml()
        temporary_path: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                dir=resolved_output.parent,
                prefix=f".{resolved_output.stem}.",
                suffix=".tmp",
                delete=False,
            ) as temporary_file:
                temporary_path = Path(temporary_file.name)
                temporary_file.write(xml)
                temporary_file.flush()
                os.fsync(temporary_file.fileno())

            os.replace(temporary_path, resolved_output)
            temporary_path = None
        finally:
            if temporary_path is not None:
                temporary_path.unlink(missing_ok=True)

        if not resolved_output.is_file():
            raise RuntimeError(f"GPX write failed: file was not created: {resolved_output}")
        if resolved_output.stat().st_size <= 0:
            raise RuntimeError(f"GPX write failed: file is empty: {resolved_output}")

        try:
            with resolved_output.open("r", encoding="utf-8") as saved_file:
                parsed = gpxpy.parse(saved_file)
        except Exception as exc:
            raise RuntimeError(
                f"GPX verification failed after saving {resolved_output}: {exc}"
            ) from exc

        saved_point_count = sum(
            len(segment.points)
            for parsed_track in parsed.tracks
            for segment in parsed_track.segments
        )
        if saved_point_count != point_count:
            raise RuntimeError(
                "GPX verification failed: "
                f"wrote {point_count} point(s) but read back {saved_point_count}."
            )

        return resolved_output
